//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace StockTraderServiceAgent
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="StockQuoteServiceSoap", Namespace="http://tempuri.org/")]
	public class StockQuoteService : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
        
		/// <remarks/>
		public StockQuoteService() 
		{
			this.Url = "http://localhost/StockQuoteExternalService/StockQuoteService.asmx";
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestQuoteExt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("QuoteExt", Namespace="http://www.bluestonepartners.com/schemas/StockTraderExt/")]
		public QuoteExt RequestQuoteExt([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTraderExt/")] string SymbolExt) 
		{
			object[] results = this.Invoke("RequestQuoteExt", new object[] {
																			   SymbolExt});
			return ((QuoteExt)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginRequestQuoteExt(string SymbolExt, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("RequestQuoteExt", new object[] {
																		SymbolExt}, callback, asyncState);
		}
        
		/// <remarks/>
		public QuoteExt EndRequestQuoteExt(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((QuoteExt)(results[0]));
		}
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTraderExt/")]
	public class QuoteExt 
	{
        
		/// <remarks/>
		public string Company_Ext;
        
		/// <remarks/>
		public System.DateTime DateTime_Ext;
        
		/// <remarks/>
		public System.Double High_Ext;
        
		/// <remarks/>
		public System.Double Low_Ext;
        
		/// <remarks/>
		public System.Double Open_Ext;
        
		/// <remarks/>
		public System.Double Last_Ext;
        
		/// <remarks/>
		public System.Double Previous_Close_Ext;
        
		/// <remarks/>
		public System.Double High_52_Week_Ext;
        
		/// <remarks/>
		public System.Double Low_52_Week_Ext;
	}
}

