using System;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
//
// Note: This class file was generated as Reference.cs under Web References / Reference.Map
//			This file was moved and renamed to the StockTraderSecureProxy.cs class file
//			because Web References can be easily updated and the modified contents of Reference.cs overwritten
// 
namespace WSSecureConvClient 
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="StockTraderServiceSoap", Namespace="http://www.bluestonepartners.com/schemas/StockTrader")]
	public class StockTraderServiceWse : Microsoft.Web.Services3.WebServicesClientProtocol
	{
        
		/// <remarks/>
		public StockTraderServiceWse() 
		{
			this.Url = "http://localhost/WSSecureConvService/StockTrader.asmx";
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bluestonepartners.com/schemas/StockTrader/RequestAllTradesSummary", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("Trades", Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
		public Trades RequestAllTradesSummary([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] string Account) 
		{
			object[] results = this.Invoke("RequestAllTradesSummary", new object[] {
																					   Account});
			return ((Trades)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginRequestAllTradesSummary(string Account, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("RequestAllTradesSummary", new object[] {
																				Account}, callback, asyncState);
		}
        
		/// <remarks/>
		public Trades EndRequestAllTradesSummary(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((Trades)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bluestonepartners.com/schemas/StockTrader/RequestTradeDetails", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("Trade", Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
		public Trade RequestTradeDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] string Account, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] string TradeID) 
		{
			object[] results = this.Invoke("RequestTradeDetails", new object[] {
																				   Account,
																				   TradeID});
			return ((Trade)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginRequestTradeDetails(string Account, string TradeID, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("RequestTradeDetails", new object[] {
																			Account,
																			TradeID}, callback, asyncState);
		}
        
		/// <remarks/>
		public Trade EndRequestTradeDetails(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((Trade)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bluestonepartners.com/schemas/StockTrader/PlaceTrade", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("Trade", Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
		public Trade PlaceTrade([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] string Account, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] string Symbol, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] int Shares, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] System.Double Price, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] TradeType tradeType) 
		{
			object[] results = this.Invoke("PlaceTrade", new object[] {
																		  Account,
																		  Symbol,
																		  Shares,
																		  Price,
																		  tradeType});
			return ((Trade)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginPlaceTrade(string Account, string Symbol, int Shares, System.Double Price, TradeType tradeType, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("PlaceTrade", new object[] {
																   Account,
																   Symbol,
																   Shares,
																   Price,
																   tradeType}, callback, asyncState);
		}
        
		/// <remarks/>
		public Trade EndPlaceTrade(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((Trade)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bluestonepartners.com/schemas/StockTrader/RequestQuote", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("Quote", Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
		public Quote RequestQuote([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")] string Symbol) 
		{
			object[] results = this.Invoke("RequestQuote", new object[] {
																			Symbol});
			return ((Quote)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginRequestQuote(string Symbol, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("RequestQuote", new object[] {
																	 Symbol}, callback, asyncState);
		}
        
		/// <remarks/>
		public Quote EndRequestQuote(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((Quote)(results[0]));
		}
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
	public class Trades 
	{
        
		/// <remarks/>
		public string Account;
        
		/// <remarks/>
		public Trade[] Bids;
        
		/// <remarks/>
		public Trade[] Asks;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
	public class Trade 
	{
        
		/// <remarks/>
		public string TradeID;
        
		/// <remarks/>
		public string Symbol;
        
		/// <remarks/>
		public System.Double Price;
        
		/// <remarks/>
		public int Shares;
        
		/// <remarks/>
		public TradeType tradeType;
        
		/// <remarks/>
		public TradeStatus tradeStatus;
        
		/// <remarks/>
		public string OrderDateTime;
        
		/// <remarks/>
		public string LastActivityDateTime;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
	public enum TradeType 
	{
        
		/// <remarks/>
		Bid,
        
		/// <remarks/>
		Ask,
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
	public enum TradeStatus 
	{
        
		/// <remarks/>
		Ordered,
        
		/// <remarks/>
		Filled,
        
		/// <remarks/>
		Cancelled,
        
		/// <remarks/>
		Unfilled,
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluestonepartners.com/schemas/StockTrader/")]
	public class Quote 
	{
        
		/// <remarks/>
		public string Symbol;
        
		/// <remarks/>
		public string Company;
        
		/// <remarks/>
		public string DateTime;
        
		/// <remarks/>
		public System.Double High;
        
		/// <remarks/>
		public System.Double Low;
        
		/// <remarks/>
		public System.Double Open;
        
		/// <remarks/>
		public System.Double Last;
        
		/// <remarks/>
		public System.Double Change;
        
		/// <remarks/>
		public System.Double PercentChange;
        
		/// <remarks/>
		public System.Double Previous_Close;
        
		/// <remarks/>
		public System.Double High_52_Week;
        
		/// <remarks/>
		public System.Double Low_52_Week;
	}
}
